name: adya_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  video_player: ^2.6.1
  google_fonts: any
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_gen: ^5.5.0+1
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.5.0+1
flutter:
  uses-material-design: true
  assets:
    - assets/

